### PR TITLE
fixed chrome warning: undefined' is not a valid enum value of interfa…

### PR DESCRIPTION
**Pull request by chafey**
…ce XMLHttpRequestResponseType

### CODE REVIEW

**Comment by geret13** [comment]
+1

**Comment by LoeLobo** [comment]
+1

**Comment by hyouuu** [comment]
+1

**Comment by dggriffin** [comment]
+1

**Comment by akshaylive** [comment]
+1

**Comment by francocatena** [comment]
+1

**Comment by tagrudev** [comment]
Anyone on this ?

**Comment by gjr-qm** [comment]
:+1:

**Comment by rafaelcorreiapoli** [comment]
+1

**Comment by JamesLefrere** [comment]
+1

**Comment by jOkes7** [comment]
+1

**Comment by Rahbaran** [comment]
+1

**Comment by tagrudev** [comment]
+1

**Comment by advany** [comment]
+1

**Comment by anddimario** [comment]
+1

**Comment by chafey** [comment]
For some reason @aldeed does not seem to be updating this library.  Perhaps someone out there wants to fork and publish it with this change?  I already have some open source libraries which I maintain and don't have the time to take on another

**Comment by ziedmahdi** [comment]
+1

**Comment by ve-koad** [comment]
+1

**Comment by mfshiu** [comment]
+1

**Pull request merged**
